export const baseStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column' as const,
    height: '100vh',
    backgroundColor: 'var(--bg-deep)',
    color: 'var(--text-primary)',
    boxSizing: 'border-box' as const,
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 24px',
    borderBottom: '1px solid var(--border-subtle)',
    backgroundColor: 'var(--bg-surface-glass)',
    backdropFilter: 'blur(10px)',
    zIndex: 10
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  logo: {
    fontSize: '28px',
    cursor: 'pointer',
  },
  title: {
    fontSize: '18px',
    fontWeight: 700,
    margin: 0,
    background: 'linear-gradient(90deg, #10b981, #0ea5e9)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    letterSpacing: '0.02em',
  },
  subtitle: {
    fontSize: '11px',
    color: 'var(--text-secondary)',
    margin: '2px 0 0 0',
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  badgeOnline: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '10px',
    fontWeight: 600,
    color: 'var(--accent-emerald)',
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
    padding: '6px 12px',
    borderRadius: '20px',
    border: '1px solid rgba(16, 185, 129, 0.2)',
    letterSpacing: '0.05em',
  },
  badgeOffline: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '10px',
    fontWeight: 600,
    color: 'var(--accent-amber)',
    backgroundColor: 'rgba(245, 158, 11, 0.08)',
    padding: '6px 12px',
    borderRadius: '20px',
    border: '1px solid rgba(245, 158, 11, 0.2)',
    letterSpacing: '0.05em',
  },
  pulseDot: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    backgroundColor: 'currentColor',
    display: 'inline-block',
  },
  toggleGroup: {
    display: 'flex',
    borderRadius: '8px',
    backgroundColor: 'var(--bg-deep)',
    padding: '3px',
    border: '1px solid var(--border-subtle)',
  },
  toggleBtn: {
    backgroundColor: 'transparent',
    color: 'var(--text-secondary)',
    border: 'none',
    borderRadius: '6px',
    padding: '6px 12px',
    fontSize: '12px',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  toggleBtnActive: {
    backgroundColor: 'var(--bg-surface)',
    color: 'var(--text-primary)',
    border: 'none',
    borderRadius: '6px',
    padding: '6px 12px',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
  },
  settingsBtn: {
    backgroundColor: 'transparent',
    color: 'var(--text-secondary)',
    border: '1px solid var(--border-subtle)',
    borderRadius: '8px',
    width: '32px',
    height: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  settingsBtnActive: {
    backgroundColor: 'var(--bg-surface)',
    color: 'var(--text-primary)',
    border: '1px solid var(--border-subtle)',
    borderRadius: '8px',
    width: '32px',
    height: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '14px',
    cursor: 'pointer',
  },
  btnPrimary: {
    backgroundColor: 'var(--accent-teal)',
    color: 'var(--bg-deep)',
    border: 'none',
    borderRadius: '8px',
    padding: '8px 16px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'transform 0.2s, opacity 0.2s, background-color 0.2s',
  },
  btnSecondary: {
    backgroundColor: 'var(--bg-surface)',
    color: 'var(--text-primary)',
    border: '1px solid var(--border-subtle)',
    borderRadius: '8px',
    padding: '8px 16px',
    fontSize: '13px',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  mainLayout: {
    display: 'flex',
    flex: 1,
    height: 'calc(100% - 73px)',
    overflow: 'hidden',
  },
  canvasContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    padding: '24px',
    overflowY: 'auto' as const,
    gap: '24px',
    backgroundColor: 'var(--bg-deep)',
  },
  searchBar: {
    display: 'flex',
    gap: '12px',
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  searchInput: {
    flex: 1,
    backgroundColor: 'var(--bg-surface)',
    border: '1px solid var(--border-subtle)',
    borderRadius: '10px',
    color: 'var(--text-primary)',
    padding: '12px 16px',
    fontSize: '13px',
    outline: 'none',
    transition: 'border-color 0.2s',
  },
  searchBtn: {
    backgroundColor: 'var(--bg-surface)',
    color: 'var(--text-primary)',
    border: '1px solid var(--border-subtle)',
    borderRadius: '10px',
    padding: '0 20px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  ragAnswerBox: {
    borderRadius: '12px',
    padding: '16px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
    border: '1px solid rgba(16, 185, 129, 0.2)',
  },
  ragHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '11px',
    color: 'var(--accent-emerald)',
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  ragText: {
    fontSize: '13px',
    color: 'var(--text-primary)',
    margin: 0,
    lineHeight: '1.6',
    whiteSpace: 'pre-wrap' as const,
  },
  archipelagoGrid: {
    flex: 1,
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '32px',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px 0',
    minHeight: '300px',
  },
  archipelagoNode: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    position: 'relative' as const,
    borderWidth: '2px',
    borderStyle: 'solid',
    boxShadow: '0 8px 32px 0 rgba(0, 0, 0, 0.15)',
    transition: 'transform 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275), border-color 0.3s',
  },
  nodeAvatar: {
    fontSize: '28px',
    marginBottom: '6px',
  },
  nodeName: {
    fontSize: '12px',
    fontWeight: 600,
    textAlign: 'center' as const,
  },
  nodeWarmth: {
    fontSize: '10px',
    fontWeight: 500,
    marginTop: '2px',
  },
  scrollableContent: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '24px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '24px',
    backgroundColor: 'var(--bg-deep)',
  },
  brainDumpCollapsed: {
    borderRadius: '14px',
    padding: '12px 20px',
    border: '1px solid var(--border-subtle)',
    marginTop: 'auto',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'var(--bg-surface-glass)',
  }
};
