export const componentStyles = {
  listView: {
    flex: 1,
    overflowY: 'auto' as const,
    minHeight: '300px',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    textAlign: 'left' as const,
  },
  tableHeaderRow: {
    borderBottom: '1px solid var(--border-subtle)',
  },
  tableHeader: {
    padding: '12px 16px',
    fontSize: '11px',
    fontWeight: 600,
    color: 'var(--text-secondary)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  tableRow: {
    borderBottom: '1px solid var(--border-subtle)',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  tableCell: {
    padding: '16px',
    fontSize: '13px',
    color: 'var(--text-primary)',
  },
  progressBarBg: {
    width: '80px',
    height: '6px',
    borderRadius: '3px',
    backgroundColor: 'var(--border-subtle)',
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: '3px',
  },
  statusTag: {
    fontSize: '10px',
    fontWeight: 700,
    padding: '4px 8px',
    borderRadius: '4px',
    letterSpacing: '0.05em',
  },
  brainDumpSection: {
    borderRadius: '14px',
    padding: '20px',
    border: '1px solid var(--border-subtle)',
    marginTop: 'auto',
  },
  sectionSubtitle: {
    fontSize: '14px',
    fontWeight: 600,
    margin: '0 0 4px 0',
  },
  sectionDesc: {
    fontSize: '11px',
    color: 'var(--text-secondary)',
    margin: '0 0 12px 0',
  },
  brainDumpTextarea: {
    width: '100%',
    boxSizing: 'border-box' as const,
    backgroundColor: 'var(--bg-deep)',
    border: '1px solid var(--border-subtle)',
    borderRadius: '10px',
    color: 'var(--text-primary)',
    padding: '12px 14px',
    fontSize: '13px',
    fontFamily: 'inherit',
    outline: 'none',
    resize: 'none' as const,
    paddingRight: '100px',
  },
  distillBtn: {
    position: 'absolute' as const,
    right: '12px',
    bottom: '12px',
    backgroundColor: 'var(--accent-teal)',
    color: 'var(--bg-deep)',
    border: 'none',
    borderRadius: '8px',
    padding: '8px 16px',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
    boxShadow: '0 4px 12px rgba(14, 165, 233, 0.15)',
  },
  detailsSidebar: {
    width: '380px',
    borderLeft: '1px solid var(--border-subtle)',
    height: '100%',
    overflowY: 'auto' as const,
    display: 'flex',
    flexDirection: 'column' as const,
    backgroundColor: 'var(--bg-surface-glass)',
  },
  sidebarContent: {
    padding: '24px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '24px',
  },
  sidebarHeader: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '8px',
    borderBottom: '1px solid var(--border-subtle)',
    paddingBottom: '20px',
  },
  avatarCircle: {
    width: '68px',
    height: '68px',
    borderRadius: '50%',
    backgroundColor: 'var(--bg-deep)',
    border: '2px solid var(--border-subtle)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '32px',
  },
  sidebarTitle: {
    fontSize: '18px',
    fontWeight: 700,
    margin: 0,
  },
  relationTag: {
    fontSize: '9px',
    fontWeight: 600,
    padding: '3px 8px',
    borderRadius: '10px',
    border: '1px solid',
  },
  sidebarStatsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '8px',
  },
  sidebarStatCard: {
    backgroundColor: 'var(--bg-deep)',
    border: '1px solid var(--border-subtle)',
    borderRadius: '8px',
    padding: '10px 6px',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '4px',
  },
  statLabel: {
    fontSize: '9px',
    color: 'var(--text-secondary)',
    textTransform: 'uppercase' as const,
  },
  statVal: {
    fontSize: '12px',
    fontWeight: 600,
    textTransform: 'capitalize' as const,
  },
  actionButtonsRow: {
    display: 'flex',
    flexDirection: 'column' as const,
  },
  btnSimulate: {
    width: '100%',
    backgroundColor: 'var(--bg-deep)',
    color: 'var(--text-primary)',
    border: '1px solid var(--border-subtle)',
    borderRadius: '8px',
    padding: '10px',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  factsSection: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '10px',
  },
  sidebarSubtitle: {
    fontSize: '11px',
    fontWeight: 600,
    color: 'var(--text-secondary)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    margin: 0,
  },
  factsList: {
    listStyleType: 'none',
    padding: 0,
    margin: 0,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  },
  factItem: {
    fontSize: '12px',
    lineHeight: '1.5',
    display: 'flex',
    gap: '8px',
    color: 'var(--text-primary)',
  },
  bullet: {
    color: 'var(--accent-emerald)',
    fontWeight: 'bold',
  },
  mementosSection: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  mementoTimeline: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '16px',
    borderLeft: '1px solid var(--border-subtle)',
    paddingLeft: '14px',
    marginLeft: '6px',
  },
  timelineItem: {
    position: 'relative' as const,
  },
  timelinePoint: {
    position: 'absolute' as const,
    left: '-18px',
    top: '4px',
    width: '7px',
    height: '7px',
    borderRadius: '50%',
    backgroundColor: 'var(--accent-teal)',
    border: '2px solid var(--bg-deep)',
  },
  timelineContent: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '4px',
  },
  timelineDate: {
    fontSize: '10px',
    color: 'var(--text-muted)',
    fontWeight: 500,
  },
  timelineNote: {
    fontSize: '12px',
    margin: 0,
    color: 'var(--text-secondary)',
    lineHeight: '1.5',
  },
  emptySidebar: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    padding: '32px',
    color: 'var(--text-secondary)',
  },
  emptyText: {
    fontSize: '12px',
    color: 'var(--text-muted)',
    margin: 0,
    fontStyle: 'italic',
  },
  errorBox: {
    backgroundColor: 'rgba(244, 63, 94, 0.08)',
    border: '1px solid rgba(244, 63, 94, 0.2)',
    borderRadius: '8px',
    padding: '12px 16px',
    color: '#fca5a5',
    fontSize: '12px',
  },
  successBox: {
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
    border: '1px solid rgba(16, 185, 129, 0.2)',
    borderRadius: '8px',
    padding: '10px 14px',
    color: '#a7f3d0',
    fontSize: '12px',
    marginTop: '12px',
  },
  modalBackdrop: {
    position: 'fixed' as const,
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    backdropFilter: 'blur(4px)',
  },
  modalContent: {
    width: '450px',
    borderRadius: '14px',
    padding: '24px',
    border: '1px solid var(--border-subtle)',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '20px',
    backgroundColor: 'var(--bg-deep)',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid var(--border-subtle)',
    paddingBottom: '12px',
  },
  closeBtn: {
    backgroundColor: 'transparent',
    color: 'var(--text-secondary)',
    border: 'none',
    fontSize: '20px',
    cursor: 'pointer',
  },
  form: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '16px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '6px',
  },
  label: {
    fontSize: '11px',
    fontWeight: 600,
    color: 'var(--text-secondary)',
    textTransform: 'uppercase' as const,
  },
  input: {
    backgroundColor: 'var(--bg-deep)',
    border: '1px solid var(--border-subtle)',
    borderRadius: '8px',
    color: 'var(--text-primary)',
    padding: '10px 12px',
    fontSize: '13px',
    outline: 'none',
  },
  select: {
    backgroundColor: 'var(--bg-surface)',
    border: '1px solid var(--border-subtle)',
    borderRadius: '8px',
    color: 'var(--text-primary)',
    padding: '10px 12px',
    fontSize: '13px',
    outline: 'none',
    width: '100%',
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    marginTop: '8px',
  },
  settingsView: {
    borderRadius: '14px',
    padding: '24px',
    border: '1px solid var(--border-subtle)',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '24px',
  },
  settingsViewTitle: {
    fontSize: '18px',
    margin: 0,
    fontWeight: 700,
  },
  settingsSection: {
    borderBottom: '1px solid var(--border-subtle)',
    paddingBottom: '20px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  settingsSectionTitle: {
    fontSize: '13px',
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    color: 'var(--text-secondary)',
    margin: 0,
  },
  lockOverlay: {
    position: 'fixed' as const,
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'var(--bg-deep)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
  },
  lockContainer: {
    width: '360px',
    borderRadius: '16px',
    padding: '32px 24px',
    border: '1px solid var(--border-subtle)',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '16px',
    textAlign: 'center' as const,
  },
  lockTitle: {
    fontSize: '20px',
    fontWeight: 700,
    margin: 0,
  },
  lockSubtitle: {
    fontSize: '12px',
    color: 'var(--text-secondary)',
    margin: '0 0 8px 0',
  },
  securityError: {
    fontSize: '11px',
    color: 'var(--accent-rose)',
    margin: 0,
  },
  debugBox: {
    marginTop: '16px',
    padding: '10px 12px',
    backgroundColor: 'rgba(245, 158, 11, 0.05)',
    border: '1px solid rgba(245, 158, 11, 0.15)',
    borderRadius: '8px',
    textAlign: 'left' as const,
  },
  code: {
    fontFamily: 'monospace',
    backgroundColor: 'var(--bg-deep)',
    padding: '2px 6px',
    borderRadius: '4px',
    fontSize: '12px',
    color: 'var(--text-primary)',
  },
  simulatedQr: {
    padding: '10px',
    backgroundColor: '#ffffff',
    borderRadius: '8px',
    boxShadow: '0 4px 16px rgba(0,0,0,0.5)',
  },
  emptyContactsBox: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    height: '350px',
    borderRadius: '12px',
    padding: '40px',
    color: 'var(--text-secondary)',
    textAlign: 'center' as const,
    border: '1px dashed var(--border-subtle)',
    gap: '8px',
  },
  controlBtn: {
    backgroundColor: 'var(--bg-surface)',
    color: 'var(--text-primary)',
    border: '1px solid var(--border-subtle)',
    borderRadius: '6px',
    padding: '4px 10px',
    fontSize: '11px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  filterRow: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap' as const,
    marginBottom: '10px',
  },
  filterChip: {
    border: '1px solid var(--border-subtle)',
    borderRadius: '20px',
    padding: '6px 14px',
    fontSize: '11px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    transition: 'all 0.2s',
  },
  contextMenuBtn: {
    display: 'block',
    width: '100%',
    padding: '8px 16px',
    backgroundColor: 'transparent',
    border: 'none',
    color: 'var(--text-primary)',
    textAlign: 'left' as const,
    fontSize: '12px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  }
};
